name: 'On Time Signs & Design'
favicon: null
layout_spectrum: 0.36161
typography_spectrum: 0.8957290325779468
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#365ba2'
    - '#d74d6e'
    - '#8c6361'
    - '#9ea2a1'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
