name: 'On Time Signs & Design'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8957290325779468
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcf9fd'
    - '#0b0905'
    - '#7fafe3'
    - '#487cb6'
    - '#4c556e'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
